### ISSUE TITLE
FATAL EXCEPTION : Can't downgrade database from version 11 to 9

### ISSUE THREAD

**Issue by Kolyall** [assist-group/assist-mcommerce-sdk-android#26]
```
  android.database.sqlite.SQLiteException: Can't downgrade database from version 11 to 9
        at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
        at ru.assisttech.sdk.storage.AssistTransactionStorageImpl.add(AssistTransactionStorageImpl.java:99)
        at ru.assisttech.sdk.engine.AssistPayEngine.startPayment(AssistPayEngine.java:327)
        at ru.assisttech.sdk.engine.AssistPayEngine.access$1200(AssistPayEngine.java:41)
        at ru.assisttech.sdk.engine.AssistPayEngine$RegistrationResultListener.onRegistrationOk(AssistPayEngine.java:486)
        at ru.assisttech.sdk.registration.AssistRegistrationProvider$RegistrationResultProcessor.syncPostProcessing(AssistRegistrationProvider.java:113)
        at ru.assisttech.sdk.network.AssistNetworkEngine$AssistNetworkTask.onPostExecute(AssistNetworkEngine.java:375)
        at ru.assisttech.sdk.network.AssistNetworkEngine$AssistNetworkTask.onPostExecute(AssistNetworkEngine.java:245)
        at android.os.AsyncTask.finish(AsyncTask.java:651)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by serg-assist** [comment]
а откуда взялась версия базы 11? по истории кода не смог найти
у вас была какая-то кастомная версия библиотеки?

**Comment by Kolyall** [comment]
нет, из 1.4.2 там была

**Comment by serg-assist** [comment]
обновил версию на 12
