### ISSUE TITLE
Ошибка NullPointerException  in == null

### ISSUE THREAD

**Issue by Kolyall** [assist-group/assist-mcommerce-sdk-android#38]
Log:
```
  [
    Response code: 200
    Response headers:
        null : HTTP/1.1 200 200 
        Connection : keep-alive 
        Content-Type : text/html;charset=UTF-8 
        Date : Tue, 04 Sep 2018 08:12:18 GMT 
        Server : nginx 
        Set-Cookie : visid_incap_955547=byFplIf2QjiACMUKbj2GRUI+jlsAAAAAQUIPAAAAAAB7RLvB2RnawpqiYdnj8J0c; expires=Tue, 03 Sep 2019 10:11:41 GMT; path=/; Domain=.paysec.by nlbi_955547=GF5YPur6vW49MEuhiZXjOgAAAACDLzq/xD7InuOa5LH8RVDz; path=/; Domain=.paysec.by incap_ses_245_955547=a1TdIXiILDl9jl1yqmpmA2E+jlsAAAAAIydqWaI0kw0d2QQtkMpTiA==; path=/; Domain=.paysec.by 
        Strict-Transport-Security : max-age=15552000;includeSubdomains 
        Transfer-Encoding : chunked 
        X-Android-Received-Millis : 1536048733707 
        X-Android-Response-Source : NETWORK 200 
        X-Android-Selected-Protocol : http/1.1 
        X-Android-Sent-Millis : 1536048733451 
        X-CDN : Incapsula 
        X-Content-Type-Options : nosniff 
        X-Frame-Options : SAMEORIGIN 
        X-Iinfo : 11-15320968-15321003 NNNN CT(0 0 0) RT(1536048737296 99) q(0 1 1 9) r(3 3) U12 
        X-XSS-Protection : 1; mode=block 
    Response data:
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head><META http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"><title>Grammofon1:5b8e3e401f8fc644a45fc401</title><link rel="StyleSheet" href="/template/styles/mobile/reset.css" type="text/css" media="screen"><link rel="StyleSheet" href="/template/styles/mobile/mobilen.css" type="text/css" media="screen"></head><!-- refresh --><script type="text/javascript"><!--var timeout;function clickAction() {frameFitting();var fr = document.getElementById('id_iframe').contentWindow.document.body.getElementsByTagName('a');for (var i=0; i<fr.length; i++) {fr[i].onclick = function() {clearInterval(timeout);timeout = setInterval("frameFitting()",100);}}}function frameFitting() {document.getElementById('id_iframe').width = '100%';document.getElementById('id_iframe').height = document.getElementById('id_iframe').contentWindow.document.body.scrollHeight+4+'px';}onload = clickAction;//--></script><body><div id="wrap"><div id="header"><div class="Logo"><img src="/template/standart/reseller_2/mobile/img/lmob.png"></div><div class="FullVersion"><a href="#">www версия</a></div></div><div id="content"><div class="Info1_result"><span>Завершено успешно </span></div><div class="Info3"><span>Заказ</span></div><div class="Info4"><span>Номер заказа : 5b8e3e401f8fc644a45fc401<br>Номер платежа : 5483439400040149<br>Покупатель: Парус Парус<br>Сумма платежа : 49.99 BYN<br></span></div><!-- GAMBLINGINFO --><!-- bannerimg --><div class="Info3"><span>Операция</span></div><iframe id="id_iframe" src="/template/standart/reseller_1/mobile/251_1.cfm?CFSID=MyYtMzcjOEM2Wz1bVVU6TCNZPlsmVi1IPiMgICAK&amp;CFID=e078d3e6-5a19-40d1-9fa0-32cf9ff987f0&amp;CFTOKEN=0" frameborder="0" vspace="0" hspace="0" marginwidth="0" marginheight="0" scrolling="no" onload = "clickAction;"></iframe><div class="Info3"><span>Магазин</span></div><div class="Info4"><span>Предприятие : Grammofon1<br>URL магазина : http://grammofon.by<br>ID предприятия : 11449616</span></div><div class="Form"><FORM method=post name=form1 action="http://succeed_payment.url/?billnumber=5483439400040149&amp;ordernumber=5b8e3e401f8fc644a45fc401&amp;payerdenial=0"><INPUT id="button" value="Вернуться в магазин" type="submit" name="Submit_Card_3"></FORM></div>	</div></div><script type="text/javascript">//<![CDATA[(function() {var _analytics_scr = document.createElement('script');_analytics_scr.type = 'text/javascript'; _analytics_scr.async = true; _analytics_scr.src = '/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3&ns=1&cb=1889058873';var _analytics_elem = docu
09-04 11:12:13.778 15048-16587/com.example.develop D/AssistWebService: Result page: HttpResponse:
    [
    Response code: 200
    Response headers:
        null : HTTP/1.1 200 200 
        Connection : keep-alive 
        Content-Type : text/html;charset=UTF-8 
        Date : Tue, 04 Sep 2018 08:12:18 GMT 
        Server : nginx 
        Set-Cookie : visid_incap_955547=byFplIf2QjiACMUKbj2GRUI+jlsAAAAAQUIPAAAAAAB7RLvB2RnawpqiYdnj8J0c; expires=Tue, 03 Sep 2019 10:11:41 GMT; path=/; Domain=.paysec.by nlbi_955547=GF5YPur6vW49MEuhiZXjOgAAAACDLzq/xD7InuOa5LH8RVDz; path=/; Domain=.paysec.by incap_ses_245_955547=a1TdIXiILDl9jl1yqmpmA2E+jlsAAAAAIydqWaI0kw0d2QQtkMpTiA==; path=/; Domain=.paysec.by 
        Strict-Transport-Security : max-age=15552000;includeSubdomains 
        Transfer-Encoding : chunked 
        X-Android-Received-Millis : 1536048733707 
        X-Android-Response-Source : NETWORK 200 
        X-Android-Selected-Protocol : http/1.1 
        X-Android-Sent-Millis : 1536048733451 
        X-CDN : Incapsula 
        X-Content-Type-Options : nosniff 
        X-Frame-Options : SAMEORIGIN 
        X-Iinfo : 11-15320968-15321003 NNNN CT(0 0 0) RT(1536048737296 99) q(0 1 1 9) r(3 3) U12 
        X-XSS-Protection : 1; mode=block 
    Response data:
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head><META http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"><title>Grammofon1:5b8e3e401f8fc644a45fc401</title><link rel="StyleSheet" href="/template/styles/mobile/reset.css" type="text/css" media="screen"><link rel="StyleSheet" href="/template/styles/mobile/mobilen.css" type="text/css" media="screen"></head><!-- refresh --><script type="text/javascript"><!--var timeout;function clickAction() {frameFitting();var fr = document.getElementById('id_iframe').contentWindow.document.body.getElementsByTagName('a');for (var i=0; i<fr.length; i++) {fr[i].onclick = function() {clearInterval(timeout);timeout = setInterval("frameFitting()",100);}}}function frameFitting() {document.getElementById('id_iframe').width = '100%';document.getElementById('id_iframe').height = document.getElementById('id_iframe').contentWindow.document.body.scrollHeight+4+'px';}onload = clickAction;//--></script><body><div id="wrap"><div id="header"><div class="Logo"><img src="/template/standart/reseller_2/mobile/img/lmob.png"></div><div class="FullVersion"><a href="#">www версия</a></div></div><div id="content"><div class="Info1_result"><span>Завершено успешно </span></div><div class="Info3"><span>Заказ</span></div><div class="Info4"><span>Номер заказа : 5b8e3e401f8fc644a45fc401<br>Номер платежа : 5483439400040149<br>Покупатель: Парус Парус<br>Сумма платежа : 49.99 BYN<br></span></div><!-- GAMBLINGINFO --><!-- bannerimg --><div class="Info3"><span>Операция</span></div><iframe id="id_iframe" src="/template/standart/reseller_1/mobile/251_1.cfm?CFSID=MyYtMzcjOEM2Wz1bVVU6TCNZPlsmVi1IPiMgICAK&amp;CFID=e078d3e6-5a19-40d1-9fa0-32cf9ff987f0&amp;CFTOKEN=0" frameborder="0" vspace="0" hspace="0" marginwidth="0" marginheight="0" scrolling="no" onload = "clickAction;"></iframe><div class="Info3"><span>Магазин</span></div><div class="Info4"><span>Предприятие : Grammofon1<br>URL магазина : http://grammofon.by<br>ID предприятия : 11449616</span></div><div class="Form"><FORM method=post name=form1 action="http://succeed_payment.url/?billnumber=5483439400040149&amp;ordernumber=5b8e3e401f8fc644a45fc401&amp;payerdenial=0"><INPUT id="button" value="Вернуться в магазин" type="submit" name="Submit_Card_3"></FORM></div>	</div></div><script type="text/javascript">//<![CDATA[(function() {var _analytics_scr = document.createElement('script');_analytics_scr.type = 'text/javascript'; _analytics_scr.async = true; _analytics_scr.src = '/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3&ns=1&cb=1889058873';var _analytics_e
```

Error:
```
09-04 11:12:14.143 15048-16587/com.example.develop E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.example.develop, PID: 15048
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ExceptionInInitializerError
        at org.jsoup.nodes.Entities.access$000(Entities.java:18)
        at org.jsoup.nodes.Entities$EscapeMode.<clinit>(Entities.java:21)
        at org.jsoup.nodes.Document$OutputSettings.<init>(Document.java:226)
        at org.jsoup.nodes.Document.<init>(Document.java:18)
        at org.jsoup.parser.TreeBuilder.initialiseParse(TreeBuilder.java:27)
        at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:40)
        at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:55)
        at org.jsoup.parser.Parser.parse(Parser.java:90)
        at org.jsoup.Jsoup.parse(Jsoup.java:58)
        at ru.assisttech.sdk.processor.AssistWebProcessor$ResultPageProcessor.asyncProcessing(AssistWebProcessor.java:387)
        at ru.assisttech.sdk.network.AssistNetworkEngine$AssistNetworkTask.doInBackground(AssistNetworkEngine.java:356)
        at ru.assisttech.sdk.network.AssistNetworkEngine$AssistNetworkTask.doInBackground(AssistNetworkEngine.java:247)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.lang.NullPointerException: in == null
        at java.util.Properties.load(Properties.java:246)
        at org.jsoup.nodes.Entities.loadEntities(Entities.java:198)
        at org.jsoup.nodes.Entities.<clinit>(Entities.java:182)
        at org.jsoup.nodes.Entities.access$000(Entities.java:18) 
        at org.jsoup.nodes.Entities$EscapeMode.<clinit>(Entities.java:21) 
        at org.jsoup.nodes.Document$OutputSettings.<init>(Document.java:226) 
        at org.jsoup.nodes.Document.<init>(Document.java:18) 
        at org.jsoup.parser.TreeBuilder.initialiseParse(TreeBuilder.java:27) 
        at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:40) 
        at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:55) 
        at org.jsoup.parser.Parser.parse(Parser.java:90) 
        at org.jsoup.Jsoup.parse(Jsoup.java:58) 
        at ru.assisttech.sdk.processor.AssistWebProcessor$ResultPageProcessor.asyncProcessing(AssistWebProcessor.java:387) 
        at ru.assisttech.sdk.network.AssistNetworkEngine$AssistNetworkTask.doInBackground(AssistNetworkEngine.java:356) 
        at ru.assisttech.sdk.network.AssistNetworkEngine$AssistNetworkTask.doInBackground(AssistNetworkEngine.java:247) 
        at android.os.AsyncTask$2.call(AsyncTask.java:295) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by Kolyall** [comment]
Исправил, добавил в gradle file , вместо jar file в libs
`api 'org.jsoup:jsoup:1.11.3'`
