### ISSUE TITLE
Падение приложения после первой оплаты

### ISSUE THREAD

**Issue by gurunbg** [assist-group/assist-mcommerce-sdk-android#51]
Добрый день
Для оплаты использеутеся метод payWeb
Ошибка проявляется только при первой оплате из приложения, последующие оплаты проходят без падения

```
E/AndroidRuntime(24529): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String ru.assisttech.sdk.storage.AssistTransaction.getOrderNumber()' on a null object reference
E/AndroidRuntime(24529): 	at ru.assisttech.sdk.processor.AssistResultProcessor.buildRequest(AssistResultProcessor.java:66)
E/AndroidRuntime(24529): 	at ru.assisttech.sdk.processor.AssistResultProcessor.run(AssistResultProcessor.java:35)
E/AndroidRuntime(24529): 	at ru.assisttech.sdk.processor.AssistBaseProcessor.start(AssistBaseProcessor.java:76)
E/AndroidRuntime(24529): 	at ru.assisttech.sdk.engine.AssistPayEngine.startProcessor(AssistPayEngine.java:408)
E/AndroidRuntime(24529): 	at ru.assisttech.sdk.engine.AssistPayEngine.getResult(AssistPayEngine.java:511)
E/AndroidRuntime(24529): 	at ru.assisttech.sdk.engine.AssistPayEngine.access$1800(AssistPayEngine.java:48)
E/AndroidRuntime(24529): 	at ru.assisttech.sdk.engine.AssistPayEngine$WebProcessorListener.onFinished(AssistPayEngine.java:723)
E/AndroidRuntime(24529): 	at ru.assisttech.sdk.processor.AssistWebProcessor$ResultPageProcessor.syncPostProcessing(AssistWebProcessor.java:469)
E/AndroidRuntime(24529): 	at ru.assisttech.sdk.network.AssistNetworkEngine$AssistNetworkTask.onPostExecute(AssistNetworkEngine.java:387)
E/AndroidRuntime(24529): 	at ru.assisttech.sdk.network.AssistNetworkEngine$AssistNetworkTask.onPostExecute(AssistNetworkEngine.java:256)
```

**Comment by tbelousov** [comment]
Добрый день, напишите, пожалуйста, об этой проблеме на support@assist.ru
